---
- name: install beanstalkd packages
  apt:
    name: {{ packages }}
    state: latest
  vars:
    packages:
      - beanstalkd

- name: setup service
  template: src=beanstalkd.j2 dest=/etc/default/beanstalkd mode=0755
  notify: restart beanstalkd
